name: "Main CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run pester Tests
        shell: pwsh
        run: |
          cd .\StringCalcKata
          Invoke-Pester
